version: "3.7"

services:
  web:
    image: patchdemon115inc/lightning.pub:1.0.0@sha256:827ef2cf492f0ce712823ac3a8057a570e0a032ecd5876d07b885b1ab2958e93
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - ${APP_LIGHTNING_NODE_DATA_DIR}:/lnd:ro
    environment:
      #LND
      LND_ADDRESS: ${APP_LIGHTNING_NODE_IP}